; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+c < %s | FileCheck %s

; End-to-end cover for the MachineInstr::NoCopyProp flag.
;
; The split copy this pass inserts is redundant in pure dataflow terms: the
; parent register still holds the value at every rewritten use. Copy
; propagation would therefore forward through it and delete it, sending the
; loads straight back to the callee-saved register the split existed to move
; them off. The flag is what stops that, and it has to survive the expansion of
; COPY into a real move as well as the copy propagation runs that follow, so
; only the emitted assembly proves the whole chain holds.
;
; The loop matters: it keeps enough values live across the call that the
; pointer cannot land in s0 or s1, the only two callee-saved registers that are
; already compressible. Without that pressure the split degenerates into an
; identity copy and the test would pass for the wrong reason.
;
; What to look for: the `mv` survives the pipeline, and the four loads address
; off a register in x8-x15 so they can encode as c.lw.

; The second function covers the opposite outcome. With little enough pressure
; the pointer wins s0, which is both callee-saved and already compressible, so
; the split buys nothing. The post-RA verification pass sees a GPRC source,
; clears NoCopyProp, and copy propagation removes the copy as it normally
; would: no `mv` should appear after the call, and the loads address off s0.
;
; Returning the pointer as well as the sum is what makes this a real test of
; the withdrawal path. It keeps the parent live past the loads, so parent and
; child overlap and the allocator cannot give them the same register. Without
; that the copy becomes an identity and the rewriter deletes it before the
; verification pass ever sees it, and the test would pass having exercised
; nothing.

declare void @h()

define i64 @split_withdrawn_parent_already_gprc(ptr readonly captures(none) %p) optsize {
; CHECK-LABEL: split_withdrawn_parent_already_gprc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    mv s0, a0
; CHECK-NEXT:    call h
; CHECK-NEXT:    lw a1, 0(s0)
; CHECK-NEXT:    lw a2, 4(s0)
; CHECK-NEXT:    lw a3, 8(s0)
; CHECK-NEXT:    lw a0, 12(s0)
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    add a0, a0, a3
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    add a0, a0, s0
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  call void @h()
  %g1 = getelementptr inbounds i32, ptr %p, i64 1
  %g2 = getelementptr inbounds i32, ptr %p, i64 2
  %g3 = getelementptr inbounds i32, ptr %p, i64 3
  %v0 = load i32, ptr %p
  %v1 = load i32, ptr %g1
  %v2 = load i32, ptr %g2
  %v3 = load i32, ptr %g3
  %a = add i32 %v0, %v1
  %b = add i32 %v2, %v3
  %c = add i32 %a, %b
  %ce = sext i32 %c to i64
  %pi = ptrtoint ptr %p to i64
  %r = add i64 %pi, %ce
  ret i64 %r
}

declare signext i32 @g(i32 signext)

define signext i32 @split_survives_copyprop(ptr readonly captures(none) %p, i32 signext %n) optsize {
; CHECK-LABEL: split_survives_copyprop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s3, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    .cfi_offset s1, -24
; CHECK-NEXT:    .cfi_offset s2, -32
; CHECK-NEXT:    .cfi_offset s3, -40
; CHECK-NEXT:    blez a1, .LBB1_3
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    mv s3, a1
; CHECK-NEXT:    mv s2, a0
; CHECK-NEXT:    li s1, 0
; CHECK-NEXT:    li s0, 0
; CHECK-NEXT:  .LBB1_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mv a0, s1
; CHECK-NEXT:    call g
; CHECK-NEXT:    mv a1, s2
; CHECK-NEXT:    lw a2, 0(a1)
; CHECK-NEXT:    lw a3, 4(a1)
; CHECK-NEXT:    lw a4, 8(a1)
; CHECK-NEXT:    add a0, a0, s0
; CHECK-NEXT:    lw a1, 12(a1)
; CHECK-NEXT:    add a0, a0, a2
; CHECK-NEXT:    add a3, a3, a4
; CHECK-NEXT:    add a0, a0, a3
; CHECK-NEXT:    addiw s1, s1, 1
; CHECK-NEXT:    addw s0, a0, a1
; CHECK-NEXT:    bne s3, s1, .LBB1_2
; CHECK-NEXT:    j .LBB1_4
; CHECK-NEXT:  .LBB1_3:
; CHECK-NEXT:    li s0, 0
; CHECK-NEXT:  .LBB1_4: # %for.cond.cleanup
; CHECK-NEXT:    mv a0, s0
; CHECK-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s3, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    .cfi_restore s3
; CHECK-NEXT:    addi sp, sp, 48
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:
  %g1 = getelementptr inbounds nuw i8, ptr %p, i64 4
  %g2 = getelementptr inbounds nuw i8, ptr %p, i64 8
  %g3 = getelementptr inbounds nuw i8, ptr %p, i64 12
  br label %for.body

for.cond.cleanup:
  %acc.lcssa = phi i32 [ 0, %entry ], [ %add7, %for.body ]
  ret i32 %acc.lcssa

for.body:
  %i = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %acc = phi i32 [ 0, %for.body.lr.ph ], [ %add7, %for.body ]
  %call = tail call signext i32 @g(i32 signext %i)
  %add = add nsw i32 %call, %acc
  %v0 = load i32, ptr %p, align 4
  %add1 = add nsw i32 %add, %v0
  %v1 = load i32, ptr %g1, align 4
  %add3 = add nsw i32 %add1, %v1
  %v2 = load i32, ptr %g2, align 4
  %add5 = add nsw i32 %add3, %v2
  %v3 = load i32, ptr %g3, align 4
  %add7 = add nsw i32 %add5, %v3
  %inc = add nuw nsw i32 %i, 1
  %done = icmp eq i32 %inc, %n
  br i1 %done, label %for.cond.cleanup, label %for.body
}
